# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='image',
        ),
        migrations.AddField(
            model_name='pic',
            name='name',
            field=models.CharField(default='car', max_length=100),
        ),
    ]
