# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_auto_20170929_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='filter',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
